# Generated by Django 2.2.2 on 2019-06-25 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_summonerstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SummonerStats',
        ),
    ]
