# Generated by Django 2.2.2 on 2019-07-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_summonerstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champId', models.CharField(max_length=200)),
                ('champName', models.CharField(max_length=200)),
                ('champIconPath', models.CharField(max_length=200)),
            ],
        ),
    ]
